functions:
  -spell-check
functionsDir: "./lint_functions"
rules:
  spelling:
    given: "$.code.API_definitions.qod-api.yaml"
    then:
      function: "spell-check"
  oas3-api-servers:
    description: "OpenAPI `servers` must be present and non-empty."
    formats: ["oas3"]
    given: "$"
    then:
      field: servers
      function: schema
      functionOptions:
        schema:
          items:
            type: object
          minItems: 1
          type: array
